# Generated by Django 3.1.8 on 2021-06-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='dete',
            new_name='date',
        ),
    ]
